# Generated by scripts/publish-homebrew-formula.sh for v0.1.95. Do not edit by
# hand: the next release overwrites this file.
class Sactl < Formula
  desc "Headless StoneAge game client for terminals and agents"
  homepage "https://github.com/k0ngk0ng/stoneage"
  version "0.1.95"
  on_macos do
    on_arm do
      url "https://github.com/k0ngk0ng/stoneage/releases/download/v0.1.95/stoneage-sactl-v0.1.95-darwin-arm64.tar.gz"
      sha256 "fb0c68be593c60438bb032cbd2fa78f7eac11ba876cb6216734019b440442d43"
    end
    on_intel do
      url "https://github.com/k0ngk0ng/stoneage/releases/download/v0.1.95/stoneage-sactl-v0.1.95-darwin-amd64.tar.gz"
      sha256 "0f9ffb323e9a8fdfbc271b9169e465756a73098026821626513c9d70df013517"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/k0ngk0ng/stoneage/releases/download/v0.1.95/stoneage-sactl-v0.1.95-linux-arm64.tar.gz"
      sha256 "b55599125d2d2273a06bf9a898343763606974f66ea1487cc0fac1c3c9d02476"
    end
    on_intel do
      url "https://github.com/k0ngk0ng/stoneage/releases/download/v0.1.95/stoneage-sactl-v0.1.95-linux-amd64.tar.gz"
      sha256 "b85dfc2e007dbf262c5ddf75e16591e1a3bb7bda83c61a0bd80b60a0e836f9bf"
    end
  end

  def install
    bin.install "sactl"
  end

  test do
    assert_match "sactl", shell_output("#{bin}/sactl version")
  end
end
