# Generated by scripts/publish-homebrew-formula.sh for v0.1.72. Do not edit by
# hand: the next release overwrites this file.
class Sactl < Formula
  desc "Headless StoneAge game client for terminals and agents"
  homepage "https://github.com/k0ngk0ng/stoneage"
  version "0.1.72"
  on_macos do
    on_arm do
      url "https://github.com/k0ngk0ng/stoneage/releases/download/v0.1.72/stoneage-sactl-v0.1.72-darwin-arm64.tar.gz"
      sha256 "b6dddd3b3ff2db985fd2737955fd40642f5e70490b1c8052a90a7d9d8cb69632"
    end
    on_intel do
      url "https://github.com/k0ngk0ng/stoneage/releases/download/v0.1.72/stoneage-sactl-v0.1.72-darwin-amd64.tar.gz"
      sha256 "772e4f2b271b00e9b3eb4cca83ef1f079341a33633bfebf59c61f15005761747"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/k0ngk0ng/stoneage/releases/download/v0.1.72/stoneage-sactl-v0.1.72-linux-arm64.tar.gz"
      sha256 "6b165d6236fd1ea5663407a914f415c47012d75c83d15fe957f4612b92bd423d"
    end
    on_intel do
      url "https://github.com/k0ngk0ng/stoneage/releases/download/v0.1.72/stoneage-sactl-v0.1.72-linux-amd64.tar.gz"
      sha256 "e6d8bf5f62940e622fa7807fdf5fe84b60c7288799272f4759c3e07cfb58afad"
    end
  end

  def install
    bin.install "sactl"
  end

  test do
    assert_match "sactl", shell_output("#{bin}/sactl version")
  end
end
