# Generated by scripts/publish-homebrew-formula.sh for v0.1.73. Do not edit by
# hand: the next release overwrites this file.
class Sactl < Formula
  desc "Headless StoneAge game client for terminals and agents"
  homepage "https://github.com/k0ngk0ng/stoneage"
  version "0.1.73"
  on_macos do
    on_arm do
      url "https://github.com/k0ngk0ng/stoneage/releases/download/v0.1.73/stoneage-sactl-v0.1.73-darwin-arm64.tar.gz"
      sha256 "8f833f22269fc7fa8f9594d14f8588b8809444f7c6aa7d8747bad4886386f085"
    end
    on_intel do
      url "https://github.com/k0ngk0ng/stoneage/releases/download/v0.1.73/stoneage-sactl-v0.1.73-darwin-amd64.tar.gz"
      sha256 "f3c7785e04e30c94eb329b59e91d0860755d910c6b182666ef0cf19d2973db32"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/k0ngk0ng/stoneage/releases/download/v0.1.73/stoneage-sactl-v0.1.73-linux-arm64.tar.gz"
      sha256 "4384eae72343632c9b5e129137b5123149cb6bb0f7f06a22644ecb3c4959172b"
    end
    on_intel do
      url "https://github.com/k0ngk0ng/stoneage/releases/download/v0.1.73/stoneage-sactl-v0.1.73-linux-amd64.tar.gz"
      sha256 "9090dca9fcc081a52661973147fe2295d89ee61f1af39918a325121880fc7049"
    end
  end

  def install
    bin.install "sactl"
  end

  test do
    assert_match "sactl", shell_output("#{bin}/sactl version")
  end
end
